version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet restore  ./awsbeanstactest/awscorewebapplication.csproj --verbosity detailed
            - dotnet build -c Release ./awsbeanstactest/awscorewebapplication.csproj --no-restore
            - dotnet test -c Release ./awsbeanstactest/awscorewebapplication.csproj
    
