version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet restore  ./awsbeanstactest/awsbeanstactest.csproj --no-restore 
            - dotnet build -c Release ./awsbeanstactest/awsbeanstactest.csproj --verbosity detailed
            - dotnet test -c Release ./awsbeanstactest/awsbeanstactest.csproj
    
