version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 3.1
pre_build:
commands:
- echo Restore started on `date`
- dotnet restore  ./awsbeanstactest/awscorewebapplication.csproj --verbosity detailed
build:
commands:
- echo Build started on `date`
- dotnet publish -c release -o ./build_output ./awsbeanstactest/awscorewebapplication.csproj --no-restore
artifacts:
  files:
    - '**/*'
  
            

    
