version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 3.1
pre_build:
    commands:
        - echo Restore started on `date`
        - dotnet restore awscorewebapplication.csproj --verbosity detailed
build:
    commands:
        - echo Build started on `date`
        - dotnet build --no-restore
artifacts:
  files:
    - .\bin\Debug\netcoreapp3.1\*
